import { GoogleGenAI, Modality, Part } from "@google/genai";

interface PhotoInput {
  base64Data: string;
  mimeType: string;
}

export const generateReunificationImage = async (
  childPhoto: PhotoInput,
  adultPhoto: PhotoInput
): Promise<string> => {
  // This is a placeholder for the API key.
  // In a real-world application, this would be handled by the environment.
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("API_KEY environment variable not set.");
  }
  
  const ai = new GoogleGenAI({ apiKey });

  const childPhotoPart: Part = {
    inlineData: {
      data: childPhoto.base64Data,
      mimeType: childPhoto.mimeType,
    },
  };

  const adultPhotoPart: Part = {
    inlineData: {
      data: adultPhoto.base64Data,
      mimeType: adultPhoto.mimeType,
    },
  };

  const prompt = `Using the two provided photos, create a new photorealistic image. The first photo is of a child, and the second is of the same person as an adult. The generated image must show the adult from the second photo hugging the child from the first photo. They should be interacting naturally and warmly. Make the lighting soft and natural. The background must be a simple, smooth, off-white studio backdrop to keep the focus on the subjects.`;
  
  const textPart: Part = {
    text: prompt,
  };
  
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [textPart, childPhotoPart, adultPhotoPart],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return part.inlineData.data;
      }
    }

    throw new Error("No image was generated by the API.");
  } catch (error) {
    console.error("Error calling Gemini API:", error);
    throw new Error("The AI model failed to process the request. Please try again.");
  }
};
